TeamPophory/pophory-server

scripts/deploy.sh
src/main/java/com/pophory/pophoryserver/domain/album/Album.java
src/main/java/com/pophory/pophoryserver/domain/album/AlbumJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialType.java
src/main/java/com/pophory/pophoryserver/domain/message/Message.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/studio/Studio.java
src/main/java/com/pophory/pophoryserver/domain/tag/GuestTag.java
src/main/java/com/pophory/pophoryserver/domain/tag/MemberTag.java
src/main/java/com/pophory/pophoryserver/global/entity/BaseTimeEntity.java

[feat #1] Entity 설계

---

build.gradle
src/main/java/com/pophory/pophoryserver/domain/album/Album.java
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java

- Resolved: #10
- 회원정보 등록 API를 구현했습니다.
- 나름 예외가 발생할만한 경우에서 throw를 해보았는데 이렇게 하는게 맞는지 모르겠습니다!!!
- MemberService 내 create 메소드에서 Album 객체를 추가해주었습니다.
- [401] Unauthorized같은 예외처리는 어디서 해주면 되는지 잘.. 모르겠어요 .. somebody help me
- response body가 따로 없어서 ResponseEntity.HeadersBuilder 타입으로 반환해주었습니다!

[feat #10] 회원정보 등록 API 구현

---

build.gradle
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/PhotoAddRequestDto.java

- Resolved: #7 
사진 추가 API를 구현했습니다.

[feat #7] 사진 추가 API 구현

---

build.gradle
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtTokenProvider.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtValidationType.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/UserAuthentication.java

- Resolved: #3 
- jwt setting,, 스밈 코드를 보고 공부했습니다ㅎㅎ
- JwtTokenProvider에서 accessToken을 생성해주고 이후 클라이언트로부터 HTTP 요청이 올 때마다 헤더에 있는 토큰과 비교하여 인증을 해주는 것이 맞나요?!
- 머지할 때 주석은 지우고 머지하겠습니당!

[feat #3] jwt setting

---

src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java

- Resolved: #16 
- 사진 삭제 API를 구현했습니다.
- 1차 스프린트에서는 Soft Delete를 적용하지 않았습니다.

[feat #16] 사진 삭제 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/PhotoAddRequestDto.java

- Resolved: #20 
사용자 정보 조회를 하는 API를 구현했습니다.

[feat #20] 사용자 정보 조회 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
src/main/java/com/pophory/pophoryserver/global/utils/PhotoUtil.java

- Resolved: #23
- 마이페이지 조회 API를 구현했습니다.
- 조언해주신대로 사진의 개수를 구하는 역할은 getPhotoCount에서, 사진 정보를 가져오는 역할은 getPhotos라는 메소드에서 할 수 있도록 구현했습니다!

[feat #23] 마이페이지 조회 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
src/main/java/com/pophory/pophoryserver/global/dto/CustomResponseDto.java
src/main/java/com/pophory/pophoryserver/global/exception/BaseException.java
src/main/java/com/pophory/pophoryserver/global/exception/PayloadTooLargeException.java
src/main/java/com/pophory/pophoryserver/global/exception/S3UploadException.java

- Resolved: #11 
- ControllerExceptionAdvice 클래스를 만들고, 적용햤습니다.

[feat #11] exception handler 생성 및 적용

---

build.gradle
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AppleAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthController.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/KakaoAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/TokenVO.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/request/AuthRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/TokenResponseDto.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/CustomJwtAuthenticationEntryPoint.java

- Resolved: #4 
- 카카오 소셜 로그인 구현
- 애플 소셜 로그인 구현
- 카카오는 토큰이 없어서 API 확인은 못해봤습니다 . .

[feat #4] 소셜로그인 API 구현 

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumListGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoListGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/vo/PhotoSizeVO.java
src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java

- Resolved: #31 
- 사진 width랑 height를 DB에 저장하고, 사진 정보 조회 시에 return 해줍니다.

[refactor #31] 사진 API 개선 및 Swagger 추가 적용

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AppleAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/KakaoAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/CustomJwtAuthenticationEntryPoint.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtTokenProvider.java
src/main/java/com/pophory/pophoryserver/global/util/MemberUtil.java

- Resolved: #28 
- JwtTokenProvider 코드 변경
- Principal 객체를 사용하여 JWT를 사용하도록 변경

[refactor #28] security 설정 변경 및 authentication 적용

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AppleAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/KakaoAuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/CustomJwtAuthenticationEntryPoint.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtTokenProvider.java
src/main/java/com/pophory/pophoryserver/global/util/MemberUtil.java

- Resolved: #42 
- SecurityConfig 수정

[fix #42] SecurityConfig 수정

---

src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthController.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
src/main/java/com/pophory/pophoryserver/global/config/jwt/CustomJwtAuthenticationEntryPoint.java
src/main/java/com/pophory/pophoryserver/global/exception/PayloadTooLargeException.java

- Resolved: #39 
- 토큰 재발급 API를 구현했습니다.
- 파일 크기가 크게 요청이 들어왔을때, `MaxUploadSizeExceededException` 이 발생해서, 맞춰서 ExceptionHandler를 변경했습니다.

[feat #39] 토큰 재발급 API 구현

---

build.gradle
scripts/deploy.sh
src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/infrastructure/s3/S3Util.java

- Resolved: #37 
- jar : false로 변경
- jvm 메모리 제한 해제
- 사진 추가시에 CloudFront로 조회 가능하게 로직 변경

[refactor #37]  배포를 위한 설정 변경

---

src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java

- Resolved: #55
- 소셜로그인 response Dto에서 boolean타입을 Boolean으로 변경했습니다.
- 사진 추가 API에서 studio 입력값 null일 경우 처리

[Fix] #55 - 사진추가 API 수정 및 소셜로그인 Response Dto명 변경

---

README.md

- Resolved: #32
- README 작성했습니다!

[docs #32] README.md 작성

---

src/main/java/com/pophory/pophoryserver/domain/album/Album.java
src/main/java/com/pophory/pophoryserver/domain/member/Member.java
src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java

- Resolved: #59 
- isRegistered를 회원가입 여부에 따라 분기 될 수 있도록 로직 변경을 진행했습니다.

[fix #59] 소셜로그인 isRegistered 기준 변경

---

build.gradle
src/main/java/com/pophory/pophoryserver/global/config/JpaQueryFactoryConfig.java

- Resolved: #38 
- querydsl 세팅을 진행했습니다.

[setting #38] querydsl 세팅

---

.github/workflows/ci.yml
.gitignore
build.gradle
src/main/java/com/pophory/pophoryserver/domain/fcm/FcmController.java
src/main/java/com/pophory/pophoryserver/domain/fcm/FcmService.java
src/main/java/com/pophory/pophoryserver/domain/fcm/dto/FcmDto.java
src/main/java/com/pophory/pophoryserver/domain/fcm/dto/MessageDto.java
src/main/java/com/pophory/pophoryserver/domain/fcm/dto/NotificationDto.java
src/main/java/com/pophory/pophoryserver/domain/fcm/dto/request/FcmRequestDto.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java

- Resolved: #70 
test push 알림 API를 구현했습니다.

[feat #70] test 푸쉬 알림 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV2Controller.java

- Resolved: #76
- V1, V2에 따라 컨트롤러 파일을 분리하였습니다.
- fcm 토큰 부분은 2차 스프린트에서 제외되기 때문에 분리하지 않았습니다!

[chore #76] v1, v2 파일 분리 및 Tag 수정

---

README.md

- Resolved: #84
- README에 서비스 소개 이미지를 추가했습니다.

[docs #84] README에 서비스 이미지 추가

---

src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java

- Resolved: #93 
사진삭제 API V2를 구현했습니다.

[feat #93] 사진 삭제 API V2 구현

---

src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java

[feat #91] 사용자 정보 조회 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetV2ResponseDto.java

- Resolved: #87 
- Album 목록조회 V2 API를 구현했습니다.

[feat #87] 앨범 목록 조회 V2 구현

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetV2ResponseDto.java

- Resolved: #85
- 마이페이지 내 정보 조회 API를 구현했습니다.
- dto도 controller처럼 V1과 V2를 나누는게 좋을까요?

[feat #85] 마이페이지 조회 API 구현 V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberGetResponseDto.java

- Resolved: #98 
사용자 정보 조회 API를 수정했습니다.

[fix #98] 사용자 정보 조회 API 수정

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java

- Resolved: #95 
앨범 단 건 조회 API를 개발했습니다.

[feat #95] 앨범 단건 조회 API 개발

---

src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java

- Resolved: #104 
- 앨범 내 사진 목록 조회 API V2를 개발했습니다.
- dev test를 위한 Access Token 만료기간 연장

[feat #104] 앨범 내 사진 목록 조회 API V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java

- Resolved: #100
- 소셜로그인 API V2 개발

[feat #100] 소셜로그인 API V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java

- Resolved: #101
- 멤버 아이디 중복체크 API V2개발

[feat #101] 멤버 아이디 중복체크 API V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/album/Album.java
src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetV2ResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumListGetV2ResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/album/repository/AlbumCustomRepository.java
src/main/java/com/pophory/pophoryserver/domain/album/repository/AlbumCustomRepositoryImpl.java
src/main/java/com/pophory/pophoryserver/domain/album/repository/AlbumJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/album/repository/AlbumRepository.java
src/main/java/com/pophory/pophoryserver/domain/auth/dto/response/TokenResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
src/main/java/com/pophory/pophoryserver/domain/photo/PhotoJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoShareController.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoShareRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetV2ResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoListGetV2ResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoShareResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoService.java
src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoShareService.java
src/main/java/com/pophory/pophoryserver/domain/s3/S3Controller.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
src/main/java/com/pophory/pophoryserver/global/util/MemberUtil.java
src/main/java/com/pophory/pophoryserver/global/util/RandomUtil.java

- Resolved: #113 
- Resolved: #114 
- 공유 관련 API 2개를 개발했습니다.
- V2 앨범 조회 API의 response에 photoLimit를 추가했습니다.
- V2 사진 조회에 sharedId를 추가했습니다. (공유를 위한)

[feat #113] 공유 관련 API 개발

---

src/main/java/com/pophory/pophoryserver/domain/studio/StudioService.java
src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioV2ResponseDto.java

- Resolved: #111
- 사진관 목록 전체 조회 API V2를 개발했습니다.
- 사진관 단건 조회 responseDto명을 StudioV2ResponseDto로, 사진관 전체 조회 responseDto명을 StudioGetResponseDto로 하였는데 더 좋은 네이밍이 있다면 추천 부탁드립니다!

[feat #111] 사진관 목록 전체 조회 API V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/version/OSType.java
src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersion.java
src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionController.java
src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionService.java
src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionListGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionUpdateRequestDto.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java

- Resolved: #120 
Version 관련 API 구현

[feat #120] Version 관련 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetV2ResponseDto.java

- Resolved: #126
- response값 수정했습니다.

[fix #126] 사진관 선택하지 않을 시 response값 NONE으로 변경

---

src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoAllListV2ResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoService.java

- Resolved: #134
- 사진 전체 조회 response에 sharedId 추가

[fix #134] 사진 전체 조회 response에 sharedId 추가

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersion.java

- Resolved: #97 
- 앨범 디자인 수정 API V2 개발

[feat #97] 앨범 디자인 수정 API V2 개발

---

src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumCover.java
src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumDesignController.java
src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumDesignService.java
src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumTheme.java
src/main/java/com/pophory/pophoryserver/domain/albumtheme/dto/response/AlbumDesignGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/albumtheme/dto/response/AlbumDesignListGetResponseDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/s3/S3Controller.java
src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java

- Resolved: #136 
앨범 디자인 정보 조회 API를 구현했습니다.

[feat #136] album design 정보 조회 API 개발

---

src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java

[fix #124] swagger 문서 편집

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java

- Resolved: #138
- AlbumDesignUpdateRequestDto 수정

[fix #138] requestDto 수정

---

src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java

- Resolved: #142
- 앨범 내 사진 조회 최신순으로 정렬했습니다!

[fix #142] 앨범 내 사진 조회 최신순으로 정렬

---

src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/auth/SocialType.java
src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoShareController.java
src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoShareService.java
src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
src/main/java/com/pophory/pophoryserver/global/exception/SelfApproveException.java
src/main/java/com/pophory/pophoryserver/global/response/ResponseCode.java

- Resolved: #140 
- 앨범 공유 수락 API에서 저장하는 data를 추가했습니다.
- 자기 자신이 공유 수락을 하는 경우를 막았습니다.

[fix #140] 앨범 공유 수락 API 로직 수정

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddV2RequestDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoShareRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoShareService.java
src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmController.java
src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java
src/main/java/com/pophory/pophoryserver/domain/pophorysm/dto/request/PophorysmShareRequestDto.java
src/main/java/com/pophory/pophoryserver/domain/version/dto/response/PophorysmGetPresignedUrlResponseDto.java

- Resolved: #128 
- 포토부스 관련 API를 구현했습니다.
- 사진 공유수락 로직을 수정했습니다.

[feat #128] 포토부스 관련 API 구현

---

src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java

- Resolved: #151 
- Access Token 만료 시간 변경
- 포포리즘 presigned url 발급 API image url 수정

[fix #151] 배포 전 버그 수정 (access token 만료 시간 변경, 포포리즘 공유 API 수정)

---

src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java

[fix #151] 포포리즘 공유시에 이미지 저장 url 변경

[fix #151] 포포리즘 공유시에 이미지 저장 url 변경

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/slack/SlackService.java

- Resolved: #158 
- slack 메세지 알림 수정이 되지 않는 문제를 수정했습니다.
- IOException을 제거했습니다.

[fix #158] slack 메세지 알림 수정

---

src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
src/main/java/com/pophory/pophoryserver/domain/slack/SlackService.java

[fix #158] 어노테이션 변경
